services:
  hotdata:
    container_name: ${NAME}
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "${PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${HOST_PATH}:/var/lib/postgresql/data/pgdata
      - .\postgresql.conf:/etc/postgresql/postgresql.conf
      - .\Logs:/etc/postgresql/logs
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'